import {
  ProyectoConstruccion,
  CapituloObra,
  PartidaObra,
  ValuacionObra,
  InsumoObra,
  RegistroBitacora,
  PartidaCatalogoCOVENIN,
} from "./types";

export const CATALOGO_PARTIDAS_COVENIN: PartidaCatalogoCOVENIN[] = [
  // 1.0 OBRAS PRELIMINARES
  {
    codigo: "E-111.100",
    capituloSugerido: "1.0 Obras Preliminares",
    descripcion: "Deforestación, tala y desraizado manual/mecánico en área de implantación de obra.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 1.85,
    rendimientoDiario: 250,
  },
  {
    codigo: "E-112.200",
    capituloSugerido: "1.0 Obras Preliminares",
    descripcion: "Demolición manual de elementos de concreto simple o armado, incluye acarreo y apilamiento.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 42.00,
    rendimientoDiario: 6,
  },
  {
    codigo: "E-121.100",
    capituloSugerido: "1.0 Obras Preliminares",
    descripcion: "Replanteo topográfico de precisión con teodolito y nivel óptico para ejes de fundación.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 0.95,
    rendimientoDiario: 500,
  },
  {
    codigo: "E-131.000",
    capituloSugerido: "1.0 Obras Preliminares",
    descripcion: "Cerca provisional perimetral en láminas de zinc h=2.00m con postes de madera y alambre de púas.",
    unidad: "ml",
    precioUnitarioEstimadoUSD: 16.50,
    rendimientoDiario: 40,
  },

  // 2.0 MOVIMIENTO DE TIERRAS
  {
    codigo: "E-211.110",
    capituloSugerido: "2.0 Movimiento de Tierras",
    descripcion: "Excavación en zanjas a mano para asiento de fundaciones y zapatas, profundidad hasta 1.50m.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 14.20,
    rendimientoDiario: 8,
  },
  {
    codigo: "E-211.200",
    capituloSugerido: "2.0 Movimiento de Tierras",
    descripcion: "Excavación con retroexcavadora en tierra compacta para sótanos y zanjas principales.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 6.80,
    rendimientoDiario: 85,
  },
  {
    codigo: "E-222.100",
    capituloSugerido: "2.0 Movimiento de Tierras",
    descripcion: "Relleno compactado con material granular clasificado (granzón), espesor capas 20cm con vibrocompactador.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 18.50,
    rendimientoDiario: 35,
  },
  {
    codigo: "E-231.100",
    capituloSugerido: "2.0 Movimiento de Tierras",
    descripcion: "Bote de escombros y tierra sobrante en camión volteo a botadero autorizado, distancia hasta 10 km.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 9.50,
    rendimientoDiario: 60,
  },

  // 3.0 ESTRUCTURAS DE CONCRETO
  {
    codigo: "E-311.110",
    capituloSugerido: "3.0 Estructuras de Concreto Armado",
    descripcion: "Concreto premezclado f'c=250 kg/cm² a los 28 días para zapatas y losas de fundación, bombeado.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 135.00,
    rendimientoDiario: 24,
  },
  {
    codigo: "E-312.110",
    capituloSugerido: "3.0 Estructuras de Concreto Armado",
    descripcion: "Concreto premezclado f'c=250 kg/cm² para pedestales, columnas y vigas de carga.",
    unidad: "m³",
    precioUnitarioEstimadoUSD: 145.00,
    rendimientoDiario: 18,
  },
  {
    codigo: "E-321.100",
    capituloSugerido: "3.0 Estructuras de Concreto Armado",
    descripcion: "Suministro, corte, doblado y colocación de acero de refuerzo cabillas estriadas fy=4200 kg/cm².",
    unidad: "kg",
    precioUnitarioEstimadoUSD: 1.65,
    rendimientoDiario: 350,
  },
  {
    codigo: "E-331.100",
    capituloSugerido: "3.0 Estructuras de Concreto Armado",
    descripcion: "Encofrado metálico o de madera cepillada para columnas rectangulares y vigas, incluye desencofrante y puntales.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 24.50,
    rendimientoDiario: 20,
  },

  // 4.0 ALBAÑILERÍA & CERRAMIENTOS
  {
    codigo: "E-411.150",
    capituloSugerido: "4.0 Albañilería & Cerramientos",
    descripcion: "Construcción de paredes con bloques de arcilla perforados e=15cm, asentados con mortero 1:4.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 17.80,
    rendimientoDiario: 14,
  },
  {
    codigo: "E-421.100",
    capituloSugerido: "4.0 Albañilería & Cerramientos",
    descripcion: "Friso rústico base sobre paredes de bloques e=1.5cm con mortero de arena lavada y cemento.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 6.20,
    rendimientoDiario: 25,
  },
  {
    codigo: "E-422.100",
    capituloSugerido: "4.0 Albañilería & Cerramientos",
    descripcion: "Friso liso de acabado sobre friso rústico con mortero cal-cemento esponjeado a plomo.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 7.90,
    rendimientoDiario: 22,
  },

  // 5.0 INSTALACIONES SANITARIAS
  {
    codigo: "E-511.400",
    capituloSugerido: "5.0 Instalaciones Sanitarias",
    descripcion: "Suministro y colocación de tubería PVC sanitaria de 4\" con accesorios y pega, para aguas servidas.",
    unidad: "ml",
    precioUnitarioEstimadoUSD: 13.40,
    rendimientoDiario: 28,
  },
  {
    codigo: "E-521.050",
    capituloSugerido: "5.0 Instalaciones Sanitarias",
    descripcion: "Tubería de PVC para aguas blancas 1/2\" soldable presurizada, con uniones, codos y tees.",
    unidad: "ml",
    precioUnitarioEstimadoUSD: 6.80,
    rendimientoDiario: 45,
  },
  {
    codigo: "E-531.100",
    capituloSugerido: "5.0 Instalaciones Sanitarias",
    descripcion: "Instalación de punto de aguas servidas para lavamanos o batea, incluye codo y bajante.",
    unidad: "pto",
    precioUnitarioEstimadoUSD: 38.00,
    rendimientoDiario: 5,
  },

  // 6.0 INSTALACIONES ELÉCTRICAS
  {
    codigo: "E-611.100",
    capituloSugerido: "6.0 Instalaciones Eléctricas",
    descripcion: "Tubería conduit metálica EMT 3/4\" empotrada en losa o pared con cajetines y conectores.",
    unidad: "ml",
    precioUnitarioEstimadoUSD: 7.50,
    rendimientoDiario: 35,
  },
  {
    codigo: "E-621.120",
    capituloSugerido: "6.0 Instalaciones Eléctricas",
    descripcion: "Cableado de conductores de cobre THW calibre #12 AWG 600V en tubería.",
    unidad: "ml",
    precioUnitarioEstimadoUSD: 1.45,
    rendimientoDiario: 120,
  },
  {
    codigo: "E-631.100",
    capituloSugerido: "6.0 Instalaciones Eléctricas",
    descripcion: "Instalación de punto de iluminación con apagador sencillo y cajetín metálico 2x4.",
    unidad: "pto",
    precioUnitarioEstimadoUSD: 26.00,
    rendimientoDiario: 8,
  },

  // 7.0 ACABADOS & PINTURA
  {
    codigo: "E-711.600",
    capituloSugerido: "7.0 Acabados & Revestimientos",
    descripcion: "Piso de porcelanato 60x60cm de alto tránsito con pegamento especial y lechada antihongos.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 28.50,
    rendimientoDiario: 12,
  },
  {
    codigo: "E-721.100",
    capituloSugerido: "7.0 Acabados & Revestimientos",
    descripcion: "Pintura de caucho elastomérica para interiores y exteriores, dos manos con sellador previo.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 4.80,
    rendimientoDiario: 45,
  },
  {
    codigo: "E-731.400",
    capituloSugerido: "7.0 Acabados & Revestimientos",
    descripcion: "Impermeabilización de losa de techo con manto asfáltico 4mm SBS con refuerzo de fibra de vidrio y pintura de aluminio reflectiva.",
    unidad: "m²",
    precioUnitarioEstimadoUSD: 16.00,
    rendimientoDiario: 30,
  },
];
export const PROYECTOS_INICIALES: ProyectoConstruccion[] = [
  {
    id: "proy-1",
    codigo: "OBR-2026-001",
    nombre: "Residencias Los Samanes - Torre A",
    clienteNombre: "Inversiones Urbanas C.A.",
    clienteRif: "J-30948211-0",
    clienteTelefono: "+58 414 123-4567",
    ubicacion: "Av. Las Delicias, Sector El Bosque, Maracay",
    ingenieroResidente: "Ing. Luis Eduardo Salazar",
    ingenieroCiv: "CIV-184.920",
    fechaInicio: "2026-01-15",
    fechaFinEstimada: "2026-11-30",
    estado: "EN_EJECUCION",
    anticipoPorcentaje: 20, // 20%
    retencionPorcentaje: 5,  // 5% fiel cumplimiento
    porcentajeAdministracion: 12, // 12%
    porcentajeUtilidad: 10,       // 10%
    porcentajeIva: 16,            // 16%
    totalPresupuestadoUSD: 68450.00,
    costoDirectoUSD: 49800.00,
    monedaPrincipal: "USD",
    notas: "Obra de estructura y acabados de torre residencial de 4 niveles.",
  },
  {
    id: "proy-2",
    codigo: "OBR-2026-002",
    nombre: "Pavimentación y Drenajes Urbanos Av. Principal",
    clienteNombre: "Consorcio Vial Centro",
    clienteRif: "J-40118922-3",
    clienteTelefono: "+58 412 888-2211",
    ubicacion: "Zona Industrial San Vicente, Maracay",
    ingenieroResidente: "Ing. Carlos Morales Peña",
    ingenieroCiv: "CIV-210.450",
    fechaInicio: "2026-03-01",
    fechaFinEstimada: "2026-08-30",
    estado: "EN_EJECUCION",
    anticipoPorcentaje: 30,
    retencionPorcentaje: 10,
    porcentajeAdministracion: 10,
    porcentajeUtilidad: 10,
    porcentajeIva: 16,
    totalPresupuestadoUSD: 45200.00,
    costoDirectoUSD: 33500.00,
    monedaPrincipal: "USD",
    notas: "Colector de aguas de lluvia y losa de pavimento rígido f'c=280.",
  },
];

export const CAPITULOS_INICIALES: CapituloObra[] = [
  { id: "cap-1", proyectoId: "proy-1", numero: "1.0", nombre: "Obras Preliminares", orden: 1 },
  { id: "cap-2", proyectoId: "proy-1", numero: "2.0", nombre: "Movimiento de Tierras", orden: 2 },
  { id: "cap-3", proyectoId: "proy-1", numero: "3.0", nombre: "Estructuras de Concreto Armado", orden: 3 },
  { id: "cap-4", proyectoId: "proy-1", numero: "4.0", nombre: "Albañilería & Cerramientos", orden: 4 },
  { id: "cap-5", proyectoId: "proy-1", numero: "5.0", nombre: "Acabados & Revestimientos", orden: 5 },
];

export const PARTIDAS_INICIALES: PartidaObra[] = [
  // Cap 1: Preliminares
  {
    id: "part-1",
    capituloId: "cap-1",
    codigoPartida: "E-111.100",
    descripcion: "Deforestación, tala y desraizado manual/mecánico en área de implantación.",
    unidad: "m²",
    cantidad: 850,
    precioUnitarioUSD: 1.85,
    totalUSD: 1572.50,
    rendimientoDiario: 250,
  },
  {
    id: "part-2",
    capituloId: "cap-1",
    codigoPartida: "E-121.100",
    descripcion: "Replanteo topográfico de precisión con nivel óptico y estacas.",
    unidad: "m²",
    cantidad: 850,
    precioUnitarioUSD: 0.95,
    totalUSD: 807.50,
    rendimientoDiario: 500,
  },

  // Cap 2: Movimiento de Tierras
  {
    id: "part-3",
    capituloId: "cap-2",
    codigoPartida: "E-211.200",
    descripcion: "Excavación con retroexcavadora para zapatas y vigas de riostra.",
    unidad: "m³",
    cantidad: 180,
    precioUnitarioUSD: 6.80,
    totalUSD: 1224.00,
    rendimientoDiario: 85,
  },
  {
    id: "part-4",
    capituloId: "cap-2",
    codigoPartida: "E-222.100",
    descripcion: "Relleno compactado con material granular (granzón) en capas de 20cm.",
    unidad: "m³",
    cantidad: 95,
    precioUnitarioUSD: 18.50,
    totalUSD: 1757.50,
    rendimientoDiario: 35,
  },

  // Cap 3: Concreto
  {
    id: "part-5",
    capituloId: "cap-3",
    codigoPartida: "E-311.110",
    descripcion: "Concreto premezclado f'c=250 kg/cm² a 28 días para fundaciones, bombeado.",
    unidad: "m³",
    cantidad: 65,
    precioUnitarioUSD: 135.00,
    totalUSD: 8775.00,
    rendimientoDiario: 24,
  },
  {
    id: "part-6",
    capituloId: "cap-3",
    codigoPartida: "E-312.110",
    descripcion: "Concreto premezclado f'c=250 kg/cm² para columnas y vigas de carga.",
    unidad: "m³",
    cantidad: 85,
    precioUnitarioUSD: 145.00,
    totalUSD: 12325.00,
    rendimientoDiario: 18,
  },
  {
    id: "part-7",
    capituloId: "cap-3",
    codigoPartida: "E-321.100",
    descripcion: "Suministro, corte, doblado y colocación de acero de refuerzo cabillas fy=4200 kg/cm².",
    unidad: "kg",
    cantidad: 7800,
    precioUnitarioUSD: 1.65,
    totalUSD: 12870.00,
    rendimientoDiario: 350,
  },
  {
    id: "part-8",
    capituloId: "cap-3",
    codigoPartida: "E-331.100",
    descripcion: "Encofrado metálico/madera para columnas y vigas con puntales telescópicos.",
    unidad: "m²",
    cantidad: 240,
    precioUnitarioUSD: 24.50,
    totalUSD: 5880.00,
    rendimientoDiario: 20,
  },

  // Cap 4: Albañilería
  {
    id: "part-9",
    capituloId: "cap-4",
    codigoPartida: "E-411.150",
    descripcion: "Paredes de bloques de arcilla perforados e=15cm asentados con mortero 1:4.",
    unidad: "m²",
    cantidad: 320,
    precioUnitarioUSD: 17.80,
    totalUSD: 5696.00,
    rendimientoDiario: 14,
  },
  {
    id: "part-10",
    capituloId: "cap-4",
    codigoPartida: "E-422.100",
    descripcion: "Friso liso sobre friso base con mortero cal-cemento esponjeado.",
    unidad: "m²",
    cantidad: 640,
    precioUnitarioUSD: 7.90,
    totalUSD: 5056.00,
    rendimientoDiario: 22,
  },
];
export const VALUACIONES_INICIALES: ValuacionObra[] = [
  {
    id: "val-1",
    proyectoId: "proy-1",
    numeroValuacion: 1,
    fechaCorte: "2026-02-15",
    periodoDesde: "2026-01-15",
    periodoHasta: "2026-02-15",
    montoBrutoUSD: 3604.00,
    amortizacionAnticipoUSD: 720.80, // 20%
    retencionGarantiaUSD: 180.20,    // 5%
    montoNetoUSD: 2703.00,
    estado: "COBRADA",
    notas: "Valuación correspondiente a replanteo, deforestación y movimiento de tierras inicial.",
    fechaRegistro: "2026-02-16",
    items: [
      {
        id: "item-val-1",
        valuacionId: "val-1",
        partidaId: "part-1",
        cantidadAnterior: 0,
        cantidadPeriodo: 850,
        cantidadAcumulada: 850,
        precioUnitarioUSD: 1.85,
        montoPeriodoUSD: 1572.50,
        porcentajeAvance: 100,
      },
      {
        id: "item-val-2",
        valuacionId: "val-1",
        partidaId: "part-2",
        cantidadAnterior: 0,
        cantidadPeriodo: 850,
        cantidadAcumulada: 850,
        precioUnitarioUSD: 0.95,
        montoPeriodoUSD: 807.50,
        porcentajeAvance: 100,
      },
      {
        id: "item-val-3",
        valuacionId: "val-1",
        partidaId: "part-3",
        cantidadAnterior: 0,
        cantidadPeriodo: 180,
        cantidadAcumulada: 180,
        precioUnitarioUSD: 6.80,
        montoPeriodoUSD: 1224.00,
        porcentajeAvance: 100,
      },
    ],
  },
  {
    id: "val-2",
    proyectoId: "proy-1",
    numeroValuacion: 2,
    fechaCorte: "2026-03-15",
    periodoDesde: "2026-02-16",
    periodoHasta: "2026-03-15",
    montoBrutoUSD: 15282.50,
    amortizacionAnticipoUSD: 3056.50, // 20%
    retencionGarantiaUSD: 764.13,     // 5%
    montoNetoUSD: 11461.87,
    estado: "APROBADA",
    notas: "Vaciado de fundaciones, zapatas y primera etapa de acero de refuerzo.",
    fechaRegistro: "2026-03-16",
    items: [
      {
        id: "item-val-4",
        valuacionId: "val-2",
        partidaId: "part-4",
        cantidadAnterior: 0,
        cantidadPeriodo: 95,
        cantidadAcumulada: 95,
        precioUnitarioUSD: 18.50,
        montoPeriodoUSD: 1757.50,
        porcentajeAvance: 100,
      },
      {
        id: "item-val-5",
        valuacionId: "val-2",
        partidaId: "part-5",
        cantidadAnterior: 0,
        cantidadPeriodo: 50,
        cantidadAcumulada: 50,
        precioUnitarioUSD: 135.00,
        montoPeriodoUSD: 6750.00,
        porcentajeAvance: 76.9,
      },
      {
        id: "item-val-6",
        valuacionId: "val-2",
        partidaId: "part-7",
        cantidadAnterior: 0,
        cantidadPeriodo: 4106,
        cantidadAcumulada: 4106,
        precioUnitarioUSD: 1.65,
        montoPeriodoUSD: 6775.00,
        porcentajeAvance: 52.6,
      },
    ],
  },
];

export const INSUMOS_INICIALES: InsumoObra[] = [
  { id: "ins-1", codigo: "MAT-001", nombre: "Cemento Gris Portland Tipo I (Saco 42.5 kg)", tipo: "MATERIAL", unidad: "saco", costoUnitarioUSD: 8.50, cantidadPresupuestada: 420, cantidadConsumida: 180, proveedor: "Cementos Catatumbo" },
  { id: "ins-2", codigo: "MAT-002", nombre: "Cabillas Estriadas 1/2\" (12m)", tipo: "MATERIAL", unidad: "barra", costoUnitarioUSD: 14.20, cantidadPresupuestada: 350, cantidadConsumida: 210, proveedor: "Siderúrgica del Turbio" },
  { id: "ins-3", codigo: "MAT-003", nombre: "Arena Lavada de Río Clasificada", tipo: "MATERIAL", unidad: "m³", costoUnitarioUSD: 22.00, cantidadPresupuestada: 65, cantidadConsumida: 30, proveedor: "Arenera Las Mayas" },
  { id: "ins-4", codigo: "MAT-004", nombre: "Piedra Picada Agregado Grueso 3/4\"", tipo: "MATERIAL", unidad: "m³", costoUnitarioUSD: 24.50, cantidadPresupuestada: 75, cantidadConsumida: 35, proveedor: "Canteras del Centro" },
  { id: "ins-5", codigo: "EQ-001", nombre: "Retroexcavadora Caterpillar 420F (Alquiler)", tipo: "EQUIPO", unidad: "hora", costoUnitarioUSD: 45.00, cantidadPresupuestada: 40, cantidadConsumida: 28, proveedor: "Maquinarias Aragua" },
  { id: "ins-6", codigo: "EQ-002", nombre: "Vibrocompactador Tipo Rana 90 kg", tipo: "EQUIPO", unidad: "día", costoUnitarioUSD: 25.00, cantidadPresupuestada: 15, cantidadConsumida: 8, proveedor: "Equipos & Andamios Pro" },
  { id: "ins-7", codigo: "MO-001", nombre: "Cuadrilla Albañilería (1 Maestro + 2 Albañiles + 2 Obreros)", tipo: "MANO_OBRA", unidad: "día", costoUnitarioUSD: 85.00, cantidadPresupuestada: 60, cantidadConsumida: 24, proveedor: "Personal Propio Obra" },
];

export const BITACORA_INICIAL: RegistroBitacora[] = [
  {
    id: "bit-1",
    proyectoId: "proy-1",
    fecha: "2026-03-18",
    clima: "SOLEADO",
    cuadrillasActivas: 2,
    obrerosPresentes: 10,
    equiposEnSitio: "1 Trompo mezclador 1 saco, 1 vibrador de concreto a gasolina, 1 torre grúa.",
    trabajosEjecutados: "Armado de acero para vigas de carga del eje 3 al 6. Colocación de separadores plásticos de recubrimiento (2.5 cm). Vaciado de 18 m³ de concreto premezclado.",
    incidencias: "Llegada del camión mixer con 30 minutos de retraso. Se tomaron 4 cilindros de prueba a compresión para ensayo a 7 y 28 días.",
    ingenieroFirma: "Ing. Luis Salazar (CIV-184.920)",
  },
  {
    id: "bit-2",
    proyectoId: "proy-1",
    fecha: "2026-03-17",
    clima: "SOLEADO",
    cuadrillasActivas: 2,
    obrerosPresentes: 12,
    equiposEnSitio: "Encofrados metálicos, puntales telescópicos y andamios tubulares.",
    trabajosEjecutados: "Nivelación y aplomado de encofrados para columnas C1 a C8. Aplicación de desmoldante ecológico. Inspección topográfica de plomos de ejes.",
    incidencias: "Jornada completada sin incidentes de seguridad laboral. Uso 100% de EPP (cascos, botas con puntera y arneses).",
    ingenieroFirma: "Ing. Luis Salazar (CIV-184.920)",
  },
];
