import { Especialista, ServicioPeluqueria, ClientePeluqueria, CitaPeluqueria, TurnoWalkIn, TransaccionCobroPeluqueria } from "./types";

export const ESPECIALISTAS_INICIALES: Especialista[] = [
  { id: "esp-1", nombre: "Valeria Rossi", rol: "Master Stylist & Colorista", telefono: "+58 412 555-1021", porcentajeComision: 45, colorAvatar: "from-pink-500 to-rose-600", activo: true },
  { id: "esp-2", nombre: "Carlos 'El Duque' Méndez", rol: "Barbero Senior & Grooming", telefono: "+58 414 777-3320", porcentajeComision: 50, colorAvatar: "from-amber-500 to-orange-600", activo: true },
  { id: "esp-3", nombre: "Sofía Mendoza", rol: "Especialista en Uñas & Manicura Rusa", telefono: "+58 424 999-4411", porcentajeComision: 40, colorAvatar: "from-purple-500 to-indigo-600", activo: true },
  { id: "esp-4", nombre: "Andrea Castillo", rol: "Tratamientos Capilares & Alisados", telefono: "+58 416 333-8822", porcentajeComision: 40, colorAvatar: "from-teal-500 to-emerald-600", activo: true },
];

export const SERVICIOS_INICIALES: ServicioPeluqueria[] = [
  { id: "srv-1", nombre: "Balayage & Iluminación Signature", categoria: "color", duracionMinutos: 150, precioUSD: 85, descripcion: "Decoloración cuidada con plex, matiz personalizado, hidratación y secado pulido." },
  { id: "srv-2", nombre: "Corte de Dama & Brushing Glamour", categoria: "corte", duracionMinutos: 50, precioUSD: 25, descripcion: "Lavado sensorial con masaje, corte personalizado según visagismo y secado con ondas." },
  { id: "srv-3", nombre: "Corte Caballero Fade & Barba Ritual", categoria: "barberia", duracionMinutos: 45, precioUSD: 18, descripcion: "Degradado afeitadora/cuchilla, perfilado de barba con toalla caliente y aceites nutritivos." },
  { id: "srv-4", nombre: "Keratina Brasileña Antifrizz", categoria: "tratamiento", duracionMinutos: 120, precioUSD: 60, descripcion: "Alisado progresivo con sellado de brillo espejo, reduce 100% el frizz." },
  { id: "srv-5", nombre: "Manicura Rusa & Semipermanente", categoria: "unas", duracionMinutos: 60, precioUSD: 20, descripcion: "Limpieza profunda de cutícula con torno y esmaltado de larga duración." },
  { id: "srv-6", nombre: "Retoque de Raíz & Baño de Brillo", categoria: "color", duracionMinutos: 75, precioUSD: 35, descripcion: "Aplicación de color en raíz y baño de luz en puntas para refrescar el tono." },
];

const fechaHaceDias = (dias: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - dias);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${dd}`;
};

const fechaHoy = (): string => {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${dd}`;
};

export const CLIENTES_INICIALES: ClientePeluqueria[] = [
  {
    id: "cli-1",
    nombre: "Camila Morales",
    telefono: "+58 412 888-9900",
    email: "camila.morales@gmail.com",
    fechaNacimiento: "1994-05-14",
    totalVisitas: 7,
    fechaUltimaVisita: fechaHaceDias(21),
    ultimoServicio: "Retoque de Raíz & Baño de Brillo",
    especialistaPreferidoId: "esp-1",
    totalGastadoUSD: 245,
    fichaTecnica: {
      tonoNatural: "Castaño Claro (Nivel 5)",
      tonoDeseado: "Rubio Cenizo 8.1",
      formulaTinte: "Igora Royal 8.1 (45g) + 20 Vol (45g) + 5g 0-22 Anti-Naranja",
      historialDecoloracion: "Decoloración suave a 20 vol en puntas (hace 3 meses)",
      sensibilidadAlergias: "Ninguna conocida. Tolera bien decolorante con plex.",
      bebidaPreferida: "Capuchino con leche de almendras y canela",
      observacionesEstilo: "Prefiere ondas abiertas al agua, nada de laca rígida.",
      ultimaActualizacion: fechaHaceDias(21),
    },
  },
  {
    id: "cli-2",
    nombre: "Valentina Henríquez",
    telefono: "+58 414 333-7711",
    email: "valen.h@outlook.com",
    totalVisitas: 4,
    fechaUltimaVisita: fechaHaceDias(23),
    ultimoServicio: "Balayage & Iluminación Signature",
    especialistaPreferidoId: "esp-1",
    totalGastadoUSD: 340,
    fichaTecnica: {
      tonoNatural: "Castano Oscuro Nivel 3",
      tonoDeseado: "Caramelo Miel",
      formulaTinte: "Decolorante Blondme 9+ con 20 Vol + Matiz 9-1 con 10 Vol",
      historialDecoloracion: "Balayage previo hace 6 meses",
      sensibilidadAlergias: "Cuero cabelludo sensible a peróxidos altos (usar protector)",
      bebidaPreferida: "Agua con gas y rodaja de limón",
      observacionesEstilo: "Le gusta el secado liso con movimiento en las puntas.",
      ultimaActualizacion: fechaHaceDias(23),
    },
  },
  {
    id: "cli-3",
    nombre: "Gabriel Mendoza",
    telefono: "+58 424 555-1234",
    totalVisitas: 12,
    fechaUltimaVisita: fechaHaceDias(21),
    ultimoServicio: "Corte Caballero Fade & Barba Ritual",
    especialistaPreferidoId: "esp-2",
    totalGastadoUSD: 216,
    fichaTecnica: {
      tonoNatural: "Negro",
      observacionesEstilo: "Skin Fade bajo en los lados, tijera arriba, barba cuadrada.",
      bebidaPreferida: "Café espresso corto sin azúcar",
      ultimaActualizacion: fechaHaceDias(21),
    },
  },
  {
    id: "cli-4",
    nombre: "Mariana Rivas",
    telefono: "+58 416 111-2233",
    totalVisitas: 2,
    fechaUltimaVisita: fechaHaceDias(3),
    ultimoServicio: "Corte de Dama & Brushing Glamour",
    especialistaPreferidoId: "esp-1",
    totalGastadoUSD: 50,
    fichaTecnica: {
      tonoNatural: "Rubio Oscuro Nivel 6",
      observacionesEstilo: "Corte en capas largas tipo mariposa (butterfly cut).",
      ultimaActualizacion: fechaHaceDias(3),
    },
  },
];

export const CITAS_INICIALES: CitaPeluqueria[] = [
  // Citas de Hoy
  {
    id: "cit-1",
    clienteId: "cli-4",
    clienteNombre: "Mariana Rivas",
    clienteTelefono: "+58 416 111-2233",
    especialistaId: "esp-1",
    especialistaNombre: "Valeria Rossi",
    servicioId: "srv-2",
    servicioNombre: "Corte de Dama & Brushing Glamour",
    fecha: fechaHoy(),
    hora: "09:30",
    duracionMinutos: 50,
    precioEstimadoUSD: 25,
    estado: "CONFIRMADA",
    esWalkIn: false,
    notas: "Viene por recomendación de Camila. Secado liso pulido.",
    fechaCreacion: fechaHoy(),
  },
  {
    id: "cit-2",
    clienteNombre: "Daniela Salazar",
    clienteTelefono: "+58 414 888-0011",
    especialistaId: "esp-1",
    especialistaNombre: "Valeria Rossi",
    servicioId: "srv-1",
    servicioNombre: "Balayage & Iluminación Signature",
    fecha: fechaHoy(),
    hora: "11:00",
    duracionMinutos: 150,
    precioEstimadoUSD: 85,
    estado: "EN_SALA",
    esWalkIn: false,
    notas: "Trae foto de referencia de tonos caramelo.",
    fechaCreacion: fechaHoy(),
  },
  {
    id: "cit-3",
    clienteNombre: "Rodrigo Bello",
    clienteTelefono: "+58 424 777-6655",
    especialistaId: "esp-2",
    especialistaNombre: "Carlos 'El Duque' Méndez",
    servicioId: "srv-3",
    servicioNombre: "Corte Caballero Fade & Barba Ritual",
    fecha: fechaHoy(),
    hora: "10:15",
    duracionMinutos: 45,
    precioEstimadoUSD: 18,
    estado: "EN_ATENCION",
    esWalkIn: false,
    fechaCreacion: fechaHoy(),
  },
  {
    id: "cit-4",
    clienteNombre: "Ana Patricia Peña",
    clienteTelefono: "+58 412 333-8899",
    especialistaId: "esp-3",
    especialistaNombre: "Sofía Mendoza",
    servicioId: "srv-5",
    servicioNombre: "Manicura Rusa & Semipermanente",
    fecha: fechaHoy(),
    hora: "14:00",
    duracionMinutos: 60,
    precioEstimadoUSD: 20,
    estado: "CONFIRMADA",
    esWalkIn: false,
    fechaCreacion: fechaHoy(),
  },
  // Citas Mañana (+1 día)
  {
    id: "cit-5",
    clienteNombre: "Carla Villegas",
    clienteTelefono: "+58 414 666-4433",
    especialistaId: "esp-1",
    especialistaNombre: "Valeria Rossi",
    servicioId: "srv-6",
    servicioNombre: "Retoque de Raíz & Baño de Brillo",
    fecha: fechaHaceDias(-1),
    hora: "10:00",
    duracionMinutos: 75,
    precioEstimadoUSD: 35,
    estado: "CONFIRMADA",
    esWalkIn: false,
    notas: "Cliente recurrente de Valeria.",
    fechaCreacion: fechaHoy(),
  },
  {
    id: "cit-6",
    clienteNombre: "Santiago Herrera",
    clienteTelefono: "+58 412 555-9988",
    especialistaId: "esp-2",
    especialistaNombre: "Carlos 'El Duque' Méndez",
    servicioId: "srv-3",
    servicioNombre: "Corte Caballero Fade & Barba Ritual",
    fecha: fechaHaceDias(-1),
    hora: "15:30",
    duracionMinutos: 45,
    precioEstimadoUSD: 18,
    estado: "CONFIRMADA",
    esWalkIn: false,
    fechaCreacion: fechaHoy(),
  },
  // Citas Pasado Mañana (+2 días)
  {
    id: "cit-7",
    clienteNombre: "Beatriz Colmenares",
    clienteTelefono: "+58 424 222-7711",
    especialistaId: "esp-4",
    especialistaNombre: "Andrea Castillo",
    servicioId: "srv-4",
    servicioNombre: "Keratina Brasileña Antifrizz",
    fecha: fechaHaceDias(-2),
    hora: "11:30",
    duracionMinutos: 120,
    precioEstimadoUSD: 60,
    estado: "CONFIRMADA",
    esWalkIn: false,
    fechaCreacion: fechaHoy(),
  },
  // Cita de Ayer (-1 día)
  {
    id: "cit-8",
    clienteNombre: "Elena Romero",
    clienteTelefono: "+58 416 888-3322",
    especialistaId: "esp-3",
    especialistaNombre: "Sofía Mendoza",
    servicioId: "srv-5",
    servicioNombre: "Manicura Rusa & Semipermanente",
    fecha: fechaHaceDias(1),
    hora: "16:00",
    duracionMinutos: 60,
    precioEstimadoUSD: 20,
    estado: "FINALIZADA",
    esWalkIn: false,
    fechaCreacion: fechaHaceDias(2),
  },
];

export const TURNOS_WALKIN_INICIALES: TurnoWalkIn[] = [
  {
    id: "tur-1",
    clienteNombre: "Jessica Blanco (Walk-in)",
    clienteTelefono: "+58 414 222-1100",
    servicioSolicitado: "Corte de Puntas & Cepillado",
    precioEstimadoUSD: 20,
    horaLlegada: "10:35",
    especialistaId: "esp-4",
    especialistaNombre: "Andrea Castillo",
    sillonOTocador: "Tocador 3",
    estado: "EN_SILLON",
    tiempoEsperaMinutos: 8,
    notas: "Cliente sin cita previa, atendida al estar libre Andrea.",
  },
  {
    id: "tur-2",
    clienteNombre: "Marcos Vivas (Walk-in)",
    clienteTelefono: "+58 412 999-5566",
    servicioSolicitado: "Corte Caballero Express",
    precioEstimadoUSD: 12,
    horaLlegada: "10:48",
    sillonOTocador: "Sillón Barbero 2",
    estado: "ESPERANDO",
    tiempoEsperaMinutos: 15,
  },
];

export const TRANSACCIONES_INICIALES: TransaccionCobroPeluqueria[] = [
  {
    id: "cob-1",
    fecha: fechaHoy(),
    hora: "09:15",
    fechaHora: `${fechaHoy()} 09:15`,
    clienteNombre: "Patricia Zambrano",
    especialistaId: "esp-1",
    especialistaNombre: "Valeria Rossi",
    servicios: [{ nombre: "Corte & Secado Glamour", precioUSD: 25 }],
    subtotalUSD: 25,
    descuentoUSD: 0,
    totalUSD: 25,
    montoBs: 912.50,
    tasaBcv: 36.50,
    metodoPago: "PAGO_MOVIL",
    referenciaPago: "PM-883921",
    porcentajeComision: 45,
    montoComisionUSD: 11.25,
    comisionEspecialistaUSD: 11.25,
    propinaUSD: 3,
    estado: "COBRADO",
  },
  {
    id: "cob-2",
    fecha: fechaHoy(),
    hora: "10:00",
    fechaHora: `${fechaHoy()} 10:00`,
    clienteNombre: "Andrés Velásquez",
    especialistaId: "esp-2",
    especialistaNombre: "Carlos 'El Duque' Méndez",
    servicios: [{ nombre: "Corte Fade & Barba", precioUSD: 18 }],
    subtotalUSD: 18,
    descuentoUSD: 0,
    totalUSD: 18,
    montoBs: 657.00,
    tasaBcv: 36.50,
    metodoPago: "EFECTIVO_USD",
    porcentajeComision: 50,
    montoComisionUSD: 9.00,
    comisionEspecialistaUSD: 9.00,
    propinaUSD: 2,
    estado: "COBRADO",
  },
];