package com.auroraplus.modules.salud;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/**
 * El portal del paciente se bloquea tras 5 fallos al confirmar la identidad. El conteo
 * de fallos debe quedar guardado: antes se lanzaba una excepcion dentro de la
 * transaccion y el rollback lo borraba, asi que el bloqueo nunca llegaba.
 */
class OdontologiaPortalBloqueoTest extends SaludIntegrationTestBase {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    // Cada peticion publica sale de una IP distinta para no chocar con el limitador por IP:
    // lo que se prueba aqui es el bloqueo propio del enlace.
    private final AtomicInteger ip = new AtomicInteger(1);

    @BeforeEach
    void crearTablaPortal() {
        // En H2 solo existen las tablas de entidades; esta la crea V85 en PostgreSQL.
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS salud_odontologia_portal_enlaces (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL, paciente_id BIGINT NOT NULL, " +
            "token_hash CHAR(64) NOT NULL UNIQUE, creado_por VARCHAR(100), fecha_creacion TIMESTAMP DEFAULT now() NOT NULL, " +
            "fecha_expiracion TIMESTAMP NOT NULL, revocado BOOLEAN DEFAULT FALSE NOT NULL, ultimo_acceso TIMESTAMP, " +
            "intentos_fallidos INTEGER DEFAULT 0 NOT NULL, bloqueado_hasta TIMESTAMP, bloqueos INTEGER DEFAULT 0 NOT NULL)");
    }

    private void fallarCincoVeces(String token) {
        for (int i = 0; i < 5; i++) verificar(token, "0000");
    }

    @Test
    void tresBloqueosDesactivanElEnlaceParaSiempre() {
        Sesion clinica = registrarClinica("Odonto Revoca " + System.nanoTime());
        long pacienteId = registrarPaciente(clinica, "V-18223344", "Luis", "Prueba");
        ResponseEntity<JsonNode> enlace = post(clinica, "/api/salud/odontologia/portal/enlaces", Map.of("pacienteId", pacienteId));
        String urlEnlace = enlace.getBody().get("url").asText();
        String token = urlEnlace.substring(urlEnlace.lastIndexOf('/') + 1);

        // Dos bloqueos: cada uno se levanta al pasar el tiempo y el enlace sigue vivo.
        for (int bloqueo = 1; bloqueo <= 2; bloqueo++) {
            fallarCincoVeces(token);
            assertEquals(bloqueo, jdbcTemplate.queryForObject(
                "SELECT bloqueos FROM salud_odontologia_portal_enlaces WHERE paciente_id = ?", Integer.class, pacienteId));
            jdbcTemplate.update("UPDATE salud_odontologia_portal_enlaces SET bloqueado_hasta = now() - INTERVAL '1' MINUTE WHERE paciente_id = ?", pacienteId);
        }

        // Tercer bloqueo: el enlace queda desactivado y ni la cedula correcta lo abre.
        for (int i = 0; i < 4; i++) verificar(token, "0000");
        ResponseEntity<JsonNode> tercero = verificar(token, "0000");
        assertEquals(HttpStatus.GONE, tercero.getStatusCode());
        assertTrue(tercero.getBody().get("message").asText().contains("desactivo"));
        assertTrue(jdbcTemplate.queryForObject(
            "SELECT revocado FROM salud_odontologia_portal_enlaces WHERE paciente_id = ?", Boolean.class, pacienteId));
        assertEquals(HttpStatus.NOT_FOUND, verificar(token, "3344").getStatusCode());
    }

    private ResponseEntity<JsonNode> verificar(String token, String respuesta) {
        HttpHeaders h = new HttpHeaders();
        h.setContentType(MediaType.APPLICATION_JSON);
        h.set("X-Forwarded-For", "10.9.0." + ip.getAndIncrement());
        return rest.exchange(url("/api/public/odontologia/portal/" + token + "/verificar"), HttpMethod.POST,
            new HttpEntity<>(Map.of("respuesta", respuesta), h), JsonNode.class);
    }

    @Test
    void cincoFallosBloqueanElEnlaceAunqueDespuesLlegueLaCedulaCorrecta() {
        Sesion clinica = registrarClinica("Odonto Bloqueo " + System.nanoTime());
        long pacienteId = registrarPaciente(clinica, "V-26407131", "Ana", "Prueba");

        ResponseEntity<JsonNode> enlace = post(clinica, "/api/salud/odontologia/portal/enlaces", Map.of("pacienteId", pacienteId));
        assertEquals(HttpStatus.OK, enlace.getStatusCode(), String.valueOf(enlace.getBody()));
        String urlEnlace = enlace.getBody().get("url").asText();
        String token = urlEnlace.substring(urlEnlace.lastIndexOf('/') + 1);

        for (int quedan = 4; quedan >= 1; quedan--) {
            ResponseEntity<JsonNode> r = verificar(token, "0000");
            assertEquals(HttpStatus.FORBIDDEN, r.getStatusCode());
            assertEquals("El dato no coincide. Le quedan " + quedan + " intento(s).", r.getBody().get("message").asText());
        }
        ResponseEntity<JsonNode> quinto = verificar(token, "0000");
        assertEquals(HttpStatus.TOO_MANY_REQUESTS, quinto.getStatusCode());
        assertTrue(quinto.getBody().get("message").asText().contains("15 minutos"));

        // Bloqueado: ni la cedula correcta abre el portal hasta que pase el tiempo.
        ResponseEntity<JsonNode> correctaBloqueada = verificar(token, "7131");
        assertEquals(HttpStatus.TOO_MANY_REQUESTS, correctaBloqueada.getStatusCode());
        assertFalse(correctaBloqueada.getBody().has("sesion"));

        // Pasado el bloqueo, la cedula correcta entrega la sesion y reinicia el conteo.
        jdbcTemplate.update("UPDATE salud_odontologia_portal_enlaces SET bloqueado_hasta = now() - INTERVAL '1' MINUTE WHERE paciente_id = ?", pacienteId);
        ResponseEntity<JsonNode> correcta = verificar(token, "7131");
        assertEquals(HttpStatus.OK, correcta.getStatusCode(), String.valueOf(correcta.getBody()));
        assertTrue(correcta.getBody().has("sesion"));
        assertEquals(0, jdbcTemplate.queryForObject(
            "SELECT intentos_fallidos FROM salud_odontologia_portal_enlaces WHERE paciente_id = ?", Integer.class, pacienteId));
    }
}
