-- Directorio de meseros por negocio (Salón & Mesas / Reportes). El nombre en
-- Comanda.mesero sigue siendo texto libre a propósito (no FK): una comanda
-- vieja conserva el nombre del mesero aunque después se desactive o se borre
-- de este directorio.
CREATE TABLE meseros_horeca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    telefono VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_meseros_horeca_tenant ON meseros_horeca(tenant_id);
