-- Reservas de mesa (Salón & Mesas) — antes no existía ninguna forma de
-- anotar "el sábado a las 8pm llega una familia de 6" dentro del sistema,
-- se llevaba aparte (agenda de papel, WhatsApp) sin ninguna visibilidad
-- para el resto del equipo.
CREATE TABLE reservas_horeca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    nombre_cliente VARCHAR(255) NOT NULL,
    telefono VARCHAR(255),
    fecha_hora TIMESTAMP NOT NULL,
    numero_personas INTEGER NOT NULL,
    numero_mesa_sugerida INTEGER,
    notas VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_reservas_horeca_tenant_fecha ON reservas_horeca(tenant_id, fecha_hora);
