-- Migracion V56: Modulo de Logistica y Despachos Pesados para Construccion
CREATE TABLE IF NOT EXISTS despachos_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT NOT NULL,
    insumo_id BIGINT,
    guia_numero VARCHAR(100) NOT NULL,
    tipo_material VARCHAR(50) NOT NULL,
    origen VARCHAR(255) NOT NULL,
    destino_frente VARCHAR(255) NOT NULL,
    unidad_transporte VARCHAR(150),
    chofer VARCHAR(150),
    estado VARCHAR(50) NOT NULL DEFAULT 'EN_TRANSITO',
    cantidad NUMERIC(14, 4) NOT NULL DEFAULT 0,
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'm3',
    peso_bruto_kg NUMERIC(14, 2),
    peso_tara_kg NUMERIC(14, 2),
    peso_neto_kg NUMERIC(14, 2),
    slump_cono_pulgadas NUMERIC(6, 2),
    fecha_hora_salida TIMESTAMP,
    fecha_hora_llegada TIMESTAMP,
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despachos_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE CASCADE,
    CONSTRAINT fk_despachos_insumo FOREIGN KEY (insumo_id) REFERENCES insumos_construccion(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_despachos_tenant_proy ON despachos_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_despachos_guia ON despachos_construccion (tenant_id, guia_numero);
