-- Migracion V57: Modulo de Maquinaria y Equipos para Construccion
CREATE TABLE IF NOT EXISTS maquinarias_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    serial_chasis VARCHAR(100),
    placa VARCHAR(50),
    horometro_actual NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    horometro_ultimo_mantenimiento NUMERIC(10, 2) DEFAULT 0.00,
    intervalo_mantenimiento_horas NUMERIC(10, 2) DEFAULT 250.00,
    estado VARCHAR(50) NOT NULL DEFAULT 'OPERATIVO',
    operador_responsable VARCHAR(150),
    costo_hora_usd NUMERIC(12, 2) DEFAULT 0.00,
    combustible_tipo VARCHAR(50) DEFAULT 'DIESEL',
    capacidad_tanque_litros NUMERIC(10, 2),
    consumo_promedio_lph NUMERIC(8, 2),
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_maquinaria_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE SET NULL,
    CONSTRAINT uk_maquinaria_tenant_codigo UNIQUE (tenant_id, codigo)
);

CREATE TABLE IF NOT EXISTS mantenimientos_maquinaria_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    maquinaria_id BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    fecha_mantenimiento DATE NOT NULL,
    horometro_en_mantenimiento NUMERIC(10, 2) NOT NULL,
    proximo_horometro_mantenimiento NUMERIC(10, 2),
    descripcion_trabajo TEXT NOT NULL,
    mecanico_o_taller VARCHAR(150),
    costo_total_usd NUMERIC(12, 2) DEFAULT 0.00,
    repuestos_utilizados TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mantenimiento_maquinaria FOREIGN KEY (maquinaria_id) REFERENCES maquinarias_construccion(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_maquinaria_tenant_proy ON maquinarias_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_maquinaria_tenant_estado ON maquinarias_construccion (tenant_id, estado);
CREATE INDEX IF NOT EXISTS idx_mantenimiento_tenant_maq ON mantenimientos_maquinaria_construccion (tenant_id, maquinaria_id);
