-- Migracion V58: Matriz de Riesgos y Seguridad Ocupacional (SST / IPERC) para Construccion
CREATE TABLE IF NOT EXISTS riesgos_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT NOT NULL,
    codigo VARCHAR(50) NOT NULL,
    proceso_frente VARCHAR(150) NOT NULL,
    peligro TEXT NOT NULL,
    riesgo_consecuencia TEXT NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    probabilidad INT NOT NULL DEFAULT 1,
    severidad INT NOT NULL DEFAULT 1,
    nivel_riesgo VARCHAR(30) NOT NULL DEFAULT 'BAJO',
    medidas_control TEXT NOT NULL,
    responsable VARCHAR(150),
    estado VARCHAR(50) NOT NULL DEFAULT 'IDENTIFICADO',
    fecha_evaluacion DATE NOT NULL,
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_riesgos_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE CASCADE,
    CONSTRAINT uk_riesgos_tenant_proy_cod UNIQUE (tenant_id, proyecto_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_riesgos_tenant_proy ON riesgos_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_riesgos_tenant_nivel ON riesgos_construccion (tenant_id, nivel_riesgo);
CREATE INDEX IF NOT EXISTS idx_riesgos_tenant_estado ON riesgos_construccion (tenant_id, estado);
