-- Migracion V59: Gestion Documental BIM / Modelos IFC / Planos y Control de RFIs para Construccion
CREATE TABLE IF NOT EXISTS documentos_bim_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT NOT NULL,
    codigo VARCHAR(50) NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    disciplina VARCHAR(50) NOT NULL,
    formato VARCHAR(30) NOT NULL,
    version VARCHAR(20) NOT NULL DEFAULT 'v1.0',
    autor_proyectista VARCHAR(150),
    archivo_url TEXT,
    peso_mb NUMERIC(10, 2),
    estado_revision VARCHAR(50) NOT NULL DEFAULT 'VIGENTE',
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documentos_bim_proy FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE CASCADE,
    CONSTRAINT uk_bim_tenant_proy_cod_ver UNIQUE (tenant_id, proyecto_id, codigo, version)
);

CREATE TABLE IF NOT EXISTS rfis_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT NOT NULL,
    documento_bim_id BIGINT,
    numero_rfi VARCHAR(50) NOT NULL,
    asunto VARCHAR(200) NOT NULL,
    disciplina VARCHAR(50) NOT NULL,
    pregunta_consulta TEXT NOT NULL,
    propuesta_solucion TEXT,
    respuesta_oficial TEXT,
    solicitante VARCHAR(150) NOT NULL,
    responsable_respuesta VARCHAR(150),
    estado VARCHAR(50) NOT NULL DEFAULT 'ABIERTO',
    fecha_limite DATE,
    fecha_respuesta DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rfis_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE CASCADE,
    CONSTRAINT fk_rfis_bim FOREIGN KEY (documento_bim_id) REFERENCES documentos_bim_construccion(id) ON DELETE SET NULL,
    CONSTRAINT uk_rfis_tenant_proy_num UNIQUE (tenant_id, proyecto_id, numero_rfi)
);

CREATE INDEX IF NOT EXISTS idx_bim_tenant_proy ON documentos_bim_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_bim_tenant_disc ON documentos_bim_construccion (tenant_id, disciplina);
CREATE INDEX IF NOT EXISTS idx_rfis_tenant_proy ON rfis_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_rfis_tenant_estado ON rfis_construccion (tenant_id, estado);
