-- Migracion V60: Planificacion Operativa de Cuadrillas y Frentes de Obra para Construccion
CREATE TABLE IF NOT EXISTS cuadrillas_construccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    proyecto_id BIGINT NOT NULL,
    partida_id BIGINT,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    especialidad VARCHAR(50) NOT NULL,
    frente_trabajo VARCHAR(150) NOT NULL,
    capataz_responsable VARCHAR(150) NOT NULL,
    cantidad_oficiales INT NOT NULL DEFAULT 1,
    cantidad_ayudantes INT NOT NULL DEFAULT 1,
    cantidad_total_personal INT NOT NULL DEFAULT 2,
    rendimiento_diario_estimado NUMERIC(10, 2),
    unidad_medida_rendimiento VARCHAR(20) DEFAULT 'm2/dia',
    estado VARCHAR(50) NOT NULL DEFAULT 'ACTIVA',
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cuadrillas_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos_construccion(id) ON DELETE CASCADE,
    CONSTRAINT fk_cuadrillas_partida FOREIGN KEY (partida_id) REFERENCES partidas_construccion(id) ON DELETE SET NULL,
    CONSTRAINT uk_cuadrillas_tenant_proy_cod UNIQUE (tenant_id, proyecto_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_cuadrillas_tenant_proy ON cuadrillas_construccion (tenant_id, proyecto_id);
CREATE INDEX IF NOT EXISTS idx_cuadrillas_tenant_estado ON cuadrillas_construccion (tenant_id, estado);
CREATE INDEX IF NOT EXISTS idx_cuadrillas_partida ON cuadrillas_construccion (partida_id);
