import {
  Empleado,
  TurnoHorario,
  AsignacionTurno,
  RegistroAsistencia,
  MetaPersonal,
  PeriodoNomina,
} from './types';

export const MOCK_TURNOS_HORARIOS: TurnoHorario[] = [
  {
    id: 'TRN-01',
    nombre: 'Mañana estándar',
    tipo: 'MANANA',
    horaInicio: '07:00',
    horaFin: '15:00',
    horasJornada: 8,
    color: '#177E89',
    descripcion: 'Consultas, apertura de restaurante y ordeño matutino',
  },
  {
    id: 'TRN-02',
    nombre: 'Tarde / servicio',
    tipo: 'TARDE',
    horaInicio: '13:00',
    horaFin: '21:00',
    horasJornada: 8,
    color: '#38bdf8',
    descripcion: 'Consultas vespertinas, servicio de salón y despacho',
  },
  {
    id: 'TRN-03',
    nombre: 'Guardia nocturna',
    tipo: 'NOCHE',
    horaInicio: '21:00',
    horaFin: '07:00',
    horasJornada: 10,
    color: '#38bdf8',
    descripcion: 'Guardia médica, ronda de potreros y cierre nocturno',
  },
  {
    id: 'TRN-04',
    nombre: 'Jornada continua de campo',
    tipo: 'JORNADA_CONTINUA',
    horaInicio: '06:00',
    horaFin: '14:00',
    horasJornada: 8,
    color: '#fbbf24',
    descripcion: 'Labores agropecuarias intensivas y producción temprana',
  },
  {
    id: 'TRN-05',
    nombre: 'Día de descanso programado',
    tipo: 'LIBRE',
    horaInicio: '--:--',
    horaFin: '--:--',
    horasJornada: 0,
    color: '#64748b',
    descripcion: 'Descanso semanal según rotación de turnos',
  },
];

export const MOCK_EMPLEADOS: Empleado[] = [
  // Vertical Salud (MediClinic)
  {
    id: 'EMP-001',
    codigoEmpleado: 'MED-0101',
    nombre: 'Dr. Alejandro',
    apellidos: 'Vargas Mendoza',
    email: 'a.vargas@aurora.demo',
    telefono: '+58 414-555-0192',
    identificacion: 'V-18.492.301',
    cargo: 'Médico Internista Principal [DEMO]',
    departamento: 'Atención & Salud',
    verticalPrincipal: 'salud',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-03-15',
    salarioBaseReferencial: 1200.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco Mercantil [DEMO]',
    cuentaReferencial: '••••-••••-1092',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 98,
  },
  {
    id: 'EMP-002',
    codigoEmpleado: 'ENF-0204',
    nombre: 'Lic. Mariana',
    apellidos: 'Contreras Silva',
    email: 'm.contreras@aurora.demo',
    telefono: '+58 424-555-4819',
    identificacion: 'V-22.109.832',
    cargo: 'Coordinadora de Triaje y Cuidados [DEMO]',
    departamento: 'Atención & Salud',
    verticalPrincipal: 'salud',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2022-08-01',
    salarioBaseReferencial: 650.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banesco [DEMO]',
    cuentaReferencial: '••••-••••-4421',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 99,
  },

  // Vertical Horeca (Restaurante / Hotelería)
  {
    id: 'EMP-003',
    codigoEmpleado: 'HOR-0301',
    nombre: 'Chef Mateo',
    apellidos: 'Lombardi Rossi',
    email: 'm.lombardi@aurora.demo',
    telefono: '+58 412-555-9012',
    identificacion: 'V-19.823.114',
    cargo: 'Chef Ejecutivo & Control de Cocina [DEMO]',
    departamento: 'Cocina & Restauración',
    verticalPrincipal: 'horeca',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-05-10',
    salarioBaseReferencial: 850.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'BBVA Provincial [DEMO]',
    cuentaReferencial: '••••-••••-8812',
    turnoAsignado: 'Tarde / Servicio [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 97,
  },
  {
    id: 'EMP-004',
    codigoEmpleado: 'HOR-0302',
    nombre: 'Srta. Camila',
    apellidos: 'Bermúdez Salas',
    email: 'c.bermudez@aurora.demo',
    telefono: '+58 416-555-3201',
    identificacion: 'V-24.312.980',
    cargo: 'Capitana de Salón & Atención al Cliente [DEMO]',
    departamento: 'Cocina & Restauración',
    verticalPrincipal: 'horeca',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-11-01',
    salarioBaseReferencial: 480.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banesco [DEMO]',
    cuentaReferencial: '••••-••••-3310',
    turnoAsignado: 'Tarde / Servicio [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 96,
  },

  // Vertical Ganadería & Campo (Agropecuaria / Finca)
  {
    id: 'EMP-005',
    codigoEmpleado: 'AGR-0501',
    nombre: 'Don Efraín',
    apellidos: 'Colmenares Parra',
    email: 'e.colmenares@aurora.demo',
    telefono: '+58 414-555-7733',
    identificacion: 'V-13.912.448',
    cargo: 'Capataz de Finca & Sanidad Bovina [DEMO]',
    departamento: 'Operaciones & Campo',
    verticalPrincipal: 'ganaderia',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2021-04-15',
    salarioBaseReferencial: 700.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco de Venezuela [DEMO]',
    cuentaReferencial: '••••-••••-9041',
    turnoAsignado: 'Jornada Continua Campo [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 100,
  },
  {
    id: 'EMP-006',
    codigoEmpleado: 'AGR-0502',
    nombre: 'Sr. José',
    apellidos: 'Montilla Briceño',
    email: 'j.montilla@aurora.demo',
    telefono: '+58 424-555-8822',
    identificacion: 'V-20.456.789',
    cargo: 'Técnico de Ordeño Mecánico & Pasturas [DEMO]',
    departamento: 'Operaciones & Campo',
    verticalPrincipal: 'ganaderia',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2022-09-01',
    salarioBaseReferencial: 450.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco Mercantil [DEMO]',
    cuentaReferencial: '••••-••••-1290',
    turnoAsignado: 'Jornada Continua Campo [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 98,
  },

  // Administración & Soporte Central
  {
    id: 'EMP-007',
    codigoEmpleado: 'ADM-0701',
    nombre: 'Lcda. Valentina',
    apellidos: 'Ríos Quintero',
    email: 'v.rios@aurora.demo',
    telefono: '+58 412-555-7711',
    identificacion: 'V-20.912.448',
    cargo: 'Coordinadora de Caja & Facturación [DEMO]',
    departamento: 'Administración & Finanzas',
    verticalPrincipal: 'general',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-01-10',
    salarioBaseReferencial: 520.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'BBVA Provincial [DEMO]',
    cuentaReferencial: '••••-••••-9801',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 96,
  },
];

export const MOCK_ASIGNACIONES_TURNOS: AsignacionTurno[] = [
  {
    id: 'ASG-101',
    empleadoId: 'EMP-001',
    empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
    empleadoCargo: 'Médico Internista [DEMO]',
    departamento: 'Atención & Salud',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'PROGRAMADO',
  },
  {
    id: 'ASG-102',
    empleadoId: 'EMP-002',
    empleadoNombre: 'Lic. Mariana Contreras Silva',
    empleadoCargo: 'Coordinadora de Triaje [DEMO]',
    departamento: 'Atención & Salud',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
  {
    id: 'ASG-103',
    empleadoId: 'EMP-003',
    empleadoNombre: 'Chef Mateo Lombardi Rossi',
    empleadoCargo: 'Chef Ejecutivo [DEMO]',
    departamento: 'Cocina & Restauración',
    fecha: '2026-09-15',
    turnoId: 'TRN-02',
    turnoNombre: 'Tarde / Servicio (13:00 - 21:00) [DEMO]',
    tipoTurno: 'TARDE',
    estado: 'PROGRAMADO',
  },
  {
    id: 'ASG-104',
    empleadoId: 'EMP-005',
    empleadoNombre: 'Don Efraín Colmenares Parra',
    empleadoCargo: 'Capataz de Finca [DEMO]',
    departamento: 'Operaciones & Campo',
    fecha: '2026-09-15',
    turnoId: 'TRN-04',
    turnoNombre: 'Jornada Continua Campo (06:00 - 14:00) [DEMO]',
    tipoTurno: 'JORNADA_CONTINUA',
    estado: 'EN_CURSO',
  },
  {
    id: 'ASG-105',
    empleadoId: 'EMP-007',
    empleadoNombre: 'Lcda. Valentina Ríos Quintero',
    empleadoCargo: 'Coordinadora de Caja [DEMO]',
    departamento: 'Administración & Finanzas',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
];

export const MOCK_REGISTROS_ASISTENCIA: RegistroAsistencia[] = [
  {
    id: 'AST-201',
    empleadoId: 'EMP-001',
    empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
    departamento: 'Atención & Salud',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '06:55',
    horaSalidaReal: '15:10',
    minutosRetardo: 0,
    horasTrabajadas: 8.25,
    horasExtras: 0.25,
    estado: 'PRESENTE',
    metodoMarcaje: 'PIN_TERMINAL',
  },
  {
    id: 'AST-202',
    empleadoId: 'EMP-002',
    empleadoNombre: 'Lic. Mariana Contreras Silva',
    departamento: 'Atención & Salud',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '07:08',
    horaSalidaReal: '15:00',
    minutosRetardo: 8,
    horasTrabajadas: 7.86,
    horasExtras: 0,
    estado: 'RETARDO',
    justificacion: 'Congestión de transporte en ruta principal [DEMO]',
    metodoMarcaje: 'PIN_TERMINAL',
  },
  {
    id: 'AST-203',
    empleadoId: 'EMP-005',
    empleadoNombre: 'Don Efraín Colmenares Parra',
    departamento: 'Operaciones & Campo',
    fecha: '2026-09-15',
    horaEntradaProgramada: '06:00',
    horaSalidaProgramada: '14:00',
    horaEntradaReal: '05:50',
    horaSalidaReal: '14:30',
    minutosRetardo: 0,
    horasTrabajadas: 8.66,
    horasExtras: 0.66,
    estado: 'PRESENTE',
    justificacion: 'Supervisión de pesaje matutino de terneros [DEMO]',
    metodoMarcaje: 'REGISTRO_SUPERVISOR',
  },
  {
    id: 'AST-204',
    empleadoId: 'EMP-007',
    empleadoNombre: 'Lcda. Valentina Ríos Quintero',
    departamento: 'Administración & Finanzas',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '06:50',
    horaSalidaReal: '15:00',
    minutosRetardo: 0,
    horasTrabajadas: 8.0,
    horasExtras: 0,
    estado: 'PRESENTE',
    metodoMarcaje: 'PIN_TERMINAL',
  },
];

export const MOCK_METAS_PERSONAL: MetaPersonal[] = [
  // Meta Vertical Salud
  {
    id: 'MET-01',
    titulo: 'Completitud de Códigos CIE-10 en Consultas [DEMO]',
    descripcion: 'Asegurar el registro del diagnóstico principal CIE-10 para alimentar el canal endémico clínico.',
    categoria: 'DOCUMENTACION',
    tipo: 'AUTOMATICA',
    origenMetrica: 'Registros de Historias Clínicas en Aurora Salud',
    departamentoObjetivo: 'Atención & Salud',
    verticalObjetivo: 'salud',
    metaValor: 95,
    unidadMedida: '% de historias',
    progresoActual: 96.5,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'COMPLETADA',
    esNoPunitiva: true,
    reconocimiento: 'Mención en cartelera médica por excelencia documental [DEMO]',
  },
  // Meta Vertical Horeca
  {
    id: 'MET-02',
    titulo: 'Tiempo Medio de Comanda en Cocina < 15 min [DEMO]',
    descripcion: 'Mantener el tiempo promedio de despacho de platos principales dentro del estándar del restaurante.',
    categoria: 'EFICIENCIA_PROCESOS',
    tipo: 'AUTOMATICA',
    origenMetrica: 'Tiempos de cierre de comandas en Aurora Horeca',
    departamentoObjetivo: 'Cocina & Restauración',
    verticalObjetivo: 'horeca',
    metaValor: 15,
    unidadMedida: 'minutos / comanda',
    progresoActual: 13.8,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'COMPLETADA',
    esNoPunitiva: true,
    reconocimiento: 'Bono de reconocimiento al equipo de cocina [DEMO]',
  },
  // Meta Vertical Ganadería
  {
    id: 'MET-03',
    titulo: 'Registro de Pesaje & Sanidad de Ganado [DEMO]',
    descripcion: 'Completar el registro quincenal de ganancia de peso y vacunación de lotes bovinos.',
    categoria: 'PRODUCCION_CAMPO',
    tipo: 'MANUAL',
    origenMetrica: 'Planilla de pesaje en báscula de manga',
    departamentoObjetivo: 'Operaciones & Campo',
    verticalObjetivo: 'ganaderia',
    metaValor: 100,
    unidadMedida: '% de lotes pesados',
    progresoActual: 85,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'EN_PROGRESO',
    esNoPunitiva: true,
  },
  // Meta General de Administración
  {
    id: 'MET-04',
    titulo: 'Puntualidad en Arqueo y Cierre de Caja [DEMO]',
    descripcion: 'Realizar el cuadre diario de tasas multi-moneda antes de las 17:30.',
    categoria: 'PUNTUALIDAD',
    tipo: 'MANUAL',
    origenMetrica: 'Bitácora de cierres de caja en Aurora Finanzas',
    departamentoObjetivo: 'Administración & Finanzas',
    verticalObjetivo: 'general',
    metaValor: 20,
    unidadMedida: 'días puntuales',
    progresoActual: 18,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'EN_PROGRESO',
    esNoPunitiva: true,
  },
];

export const MOCK_PERIODOS_NOMINA: PeriodoNomina[] = [
  {
    id: 'PER-2026-09-Q1',
    codigoPeriodo: 'NOM-2026-09-Q1',
    nombre: '1ra Quincena Septiembre 2026 [DEMO]',
    fechaInicio: '2026-09-01',
    fechaFin: '2026-09-15',
    fechaTentativaPago: '2026-09-15',
    estado: 'BORRADOR',
    totalEmpleados: 7,
    montoTotalBruto: 2425.0,
    montoTotalDeducciones: 175.0,
    montoTotalNeto: 2250.0,
    monedaPrincipal: 'USD',
    notasAuditoria: 'Período en borrador preliminar. Módulo opcional desactivado por defecto.',
    historialAjustes: [],
    recibos: [
      {
        id: 'REC-001',
        empleadoId: 'EMP-001',
        empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
        empleadoCargo: 'Médico Internista Principal [DEMO]',
        departamento: 'Atención & Salud',
        diasTrabajados: 15,
        horasExtrasTotal: 2,
        totalPercepciones: 630.0,
        totalDeducciones: 45.0,
        montoNetoPagar: 585.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base quincenal',
            baseCalculoMascara: '15 días laborados sobre base convenida',
            reglaAplicada: 'Sueldo base mensual / 2',
            vigencia: 'Tabulador General Q3-2026 [DEMO]',
            monto: 600.0,
            moneda: 'USD',
          },
          {
            concepto: 'Incentivo por Calidad & Documentación [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: 'Meta CIE-10 superada al 96.5%',
            baseCalculoMascara: 'Cumplimiento de meta formativa',
            reglaAplicada: 'Monto voluntario de estímulo profesional',
            vigencia: 'Política de incentivos [DEMO]',
            monto: 30.0,
            moneda: 'USD',
          },
          {
            concepto: 'Aporte Póliza Colectiva de Salud [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Cuota de póliza de salud voluntaria',
            baseCalculoMascara: 'Cuota acordada de póliza',
            reglaAplicada: 'Retención fija quincenal acordada',
            vigencia: 'Convenio de póliza 2026 [DEMO]',
            monto: 45.0,
            moneda: 'USD',
          },
        ],
      },
      {
        id: 'REC-002',
        empleadoId: 'EMP-003',
        empleadoNombre: 'Chef Mateo Lombardi Rossi',
        empleadoCargo: 'Chef Ejecutivo [DEMO]',
        departamento: 'Cocina & Restauración',
        diasTrabajados: 15,
        horasExtrasTotal: 4,
        totalPercepciones: 455.0,
        totalDeducciones: 30.0,
        montoNetoPagar: 425.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base quincenal',
            baseCalculoMascara: '15 días laborados sobre base convenida',
            reglaAplicada: 'Sueldo base mensual / 2',
            vigencia: 'Tabulador Gastronomía [DEMO]',
            monto: 425.0,
            moneda: 'USD',
          },
          {
            concepto: 'Compensación por Servicio Extraordinario [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '4 horas de soporte en evento gastronómico',
            baseCalculoMascara: 'Horas extraordinarias de servicio',
            reglaAplicada: 'Tarifa hora especial acordada ($7.50 / h)',
            vigencia: 'Reglamento de eventos [DEMO]',
            monto: 30.0,
            moneda: 'USD',
          },
          {
            concepto: 'Deducción de Uniforme Técnico [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Amortización de dotación de cocina',
            baseCalculoMascara: 'Descuento de dotación',
            reglaAplicada: 'Cuota fija convenio dotación',
            vigencia: 'Acuerdo interno [DEMO]',
            monto: 30.0,
            moneda: 'USD',
          },
        ],
      },
      {
        id: 'REC-003',
        empleadoId: 'EMP-005',
        empleadoNombre: 'Don Efraín Colmenares Parra',
        empleadoCargo: 'Capataz de Finca [DEMO]',
        departamento: 'Operaciones & Campo',
        diasTrabajados: 15,
        horasExtrasTotal: 6,
        totalPercepciones: 395.0,
        totalDeducciones: 20.0,
        montoNetoPagar: 375.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base quincenal',
            baseCalculoMascara: '15 días laborados sobre base convenida',
            reglaAplicada: 'Sueldo base mensual / 2',
            vigencia: 'Tabulador Agropecuario [DEMO]',
            monto: 350.0,
            moneda: 'USD',
          },
          {
            concepto: 'Bonificación por Manejo de Lote Bovino [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: 'Supervisión exitosa de ciclo de pesaje',
            baseCalculoMascara: 'Estímulo de manejo de campo',
            reglaAplicada: 'Bono fijo por cumplimiento de ciclo',
            vigencia: 'Plan de incentivos de campo [DEMO]',
            monto: 45.0,
            moneda: 'USD',
          },
          {
            concepto: 'Fondo de Ahorro Rural [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Aporte voluntario de ahorro',
            baseCalculoMascara: 'Aporte de caja de ahorro',
            reglaAplicada: 'Retención autorizada por colaborador',
            vigencia: 'Caja de ahorro [DEMO]',
            monto: 20.0,
            moneda: 'USD',
          },
        ],
      },
    ],
  },
];
