import {
  Empleado,
  TurnoHorario,
  AsignacionTurno,
  RegistroAsistencia,
  MetaPersonal,
  PeriodoNomina,
} from './types';

export const MOCK_TURNOS_HORARIOS: TurnoHorario[] = [
  {
    id: 'TRN-01',
    nombre: 'Mañana Estándar [DEMO]',
    tipo: 'MANANA',
    horaInicio: '07:00',
    horaFin: '15:00',
    horasJornada: 8,
    color: '#35d7c3',
    descripcion: 'Atención ambulatoria y consultas matutinas',
  },
  {
    id: 'TRN-02',
    nombre: 'Tarde Asistencial [DEMO]',
    tipo: 'TARDE',
    horaInicio: '13:00',
    horaFin: '21:00',
    horasJornada: 8,
    color: '#38bdf8',
    descripcion: 'Turno de tarde, emergencias diurnas y soporte',
  },
  {
    id: 'TRN-03',
    nombre: 'Guardia Nocturna [DEMO]',
    tipo: 'NOCHE',
    horaInicio: '21:00',
    horaFin: '07:00',
    horasJornada: 10,
    color: '#818cf8',
    descripcion: 'Guardia nocturna hospitalaria y triaje continuo',
  },
  {
    id: 'TRN-04',
    nombre: 'Guardia Integral 24H [DEMO]',
    tipo: 'GUARDIA_24H',
    horaInicio: '08:00',
    horaFin: '08:00',
    horasJornada: 24,
    color: '#fbbf24',
    descripcion: 'Médicos de guardia en fin de semana / urgencias',
  },
  {
    id: 'TRN-05',
    nombre: 'Día Libre Programado [DEMO]',
    tipo: 'LIBRE',
    horaInicio: '--:--',
    horaFin: '--:--',
    horasJornada: 0,
    color: '#64748b',
    descripcion: 'Descanso semanal reglamentario',
  },
];

export const MOCK_EMPLEADOS: Empleado[] = [
  {
    id: 'EMP-001',
    codigoEmpleado: 'MED-0101',
    nombre: 'Dr. Alejandro',
    apellidos: 'Vargas Mendoza',
    email: 'a.vargas@auroramediclinic.demo',
    telefono: '+58 414-555-0192',
    identificacion: 'V-18.492.301',
    cargo: 'Médico Internista Principal [DEMO]',
    departamento: 'Médico',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-03-15',
    salarioBaseReferencial: 1200.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco Mercantil [DEMO]',
    cuentaReferencial: '••••-••••-1092',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 98,
  },
  {
    id: 'EMP-002',
    codigoEmpleado: 'ENF-0204',
    nombre: 'Lic. Mariana',
    apellidos: 'Contreras Silva',
    email: 'm.contreras@auroramediclinic.demo',
    telefono: '+58 424-555-4819',
    identificacion: 'V-22.109.832',
    cargo: 'Jefa de Enfermería y Triaje [DEMO]',
    departamento: 'Enfermería',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2022-08-01',
    salarioBaseReferencial: 650.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banesco [DEMO]',
    cuentaReferencial: '••••-••••-4421',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 3,
    asistenciaTasaMes: 99,
  },
  {
    id: 'EMP-003',
    codigoEmpleado: 'ADM-0301',
    nombre: 'Lcda. Valentina',
    apellidos: 'Ríos Quintero',
    email: 'v.rios@auroramediclinic.demo',
    telefono: '+58 412-555-7711',
    identificacion: 'V-20.912.448',
    cargo: 'Coordinadora de Admisión y Caja [DEMO]',
    departamento: 'Administración',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-01-10',
    salarioBaseReferencial: 500.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'BBVA Provincial [DEMO]',
    cuentaReferencial: '••••-••••-9801',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 96,
  },
  {
    id: 'EMP-004',
    codigoEmpleado: 'MED-0105',
    nombre: 'Dra. Elena',
    apellidos: 'Peralta Santos',
    email: 'e.peralta@auroramediclinic.demo',
    telefono: '+58 416-555-3210',
    identificacion: 'V-16.782.903',
    cargo: 'Especialista en Pediatría [DEMO]',
    departamento: 'Médico',
    tipoContrato: 'POR_HONORARIOS',
    estado: 'ACTIVO',
    fechaIngreso: '2024-02-01',
    salarioBaseReferencial: 950.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco de Venezuela [DEMO]',
    cuentaReferencial: '••••-••••-3329',
    turnoAsignado: 'Tarde Asistencial [DEMO]',
    metasActivasCount: 2,
    asistenciaTasaMes: 100,
  },
  {
    id: 'EMP-005',
    codigoEmpleado: 'LAB-0402',
    nombre: 'Bioan. Carlos',
    apellidos: 'Gómez Benítez',
    email: 'c.gomez@auroramediclinic.demo',
    telefono: '+58 414-555-9082',
    identificacion: 'V-19.456.128',
    cargo: 'Bioanalista Encargado [DEMO]',
    departamento: 'Laboratorio / Farmacia',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2023-06-20',
    salarioBaseReferencial: 600.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Bancaribe [DEMO]',
    cuentaReferencial: '••••-••••-7123',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 97,
  },
  {
    id: 'EMP-006',
    codigoEmpleado: 'OPR-0501',
    nombre: 'Sr. Roberto',
    apellidos: 'Machado Gil',
    email: 'r.machado@auroramediclinic.demo',
    telefono: '+58 424-555-6612',
    identificacion: 'V-14.321.890',
    cargo: 'Supervisor de Mantenimiento y Esterilización [DEMO]',
    departamento: 'Operaciones / Servicios',
    tipoContrato: 'TIEMPO_COMPLETO',
    estado: 'ACTIVO',
    fechaIngreso: '2021-11-15',
    salarioBaseReferencial: 420.0,
    moneda: 'USD',
    modalidadPago: 'QUINCENAL',
    bancoReferencial: 'Banco Mercantil [DEMO]',
    cuentaReferencial: '••••-••••-5582',
    turnoAsignado: 'Mañana Estándar [DEMO]',
    metasActivasCount: 1,
    asistenciaTasaMes: 95,
  },
  {
    id: 'EMP-007',
    codigoEmpleado: 'SOP-0601',
    nombre: 'Ing. Gabriela',
    apellidos: 'Salazar Uribe',
    email: 'g.salazar@auroramediclinic.demo',
    telefono: '+58 412-555-0941',
    identificacion: 'V-23.784.102',
    cargo: 'Especialista de Sistemas y Soporte IT [DEMO]',
    departamento: 'Soporte y Sistemas',
    tipoContrato: 'MEDIO_TIEMPO',
    estado: 'DE_VACACIONES',
    fechaIngreso: '2023-09-01',
    salarioBaseReferencial: 480.0,
    moneda: 'USD',
    modalidadPago: 'MENSUAL',
    bancoReferencial: 'Banesco [DEMO]',
    cuentaReferencial: '••••-••••-9012',
    turnoAsignado: 'Tarde Asistencial [DEMO]',
    metasActivasCount: 0,
    asistenciaTasaMes: 100,
  },
];

export const MOCK_ASIGNACIONES_TURNOS: AsignacionTurno[] = [
  {
    id: 'ASG-101',
    empleadoId: 'EMP-001',
    empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
    empleadoCargo: 'Médico Internista Principal [DEMO]',
    departamento: 'Médico',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'PROGRAMADO',
  },
  {
    id: 'ASG-102',
    empleadoId: 'EMP-002',
    empleadoNombre: 'Lic. Mariana Contreras Silva',
    empleadoCargo: 'Jefa de Enfermería y Triaje [DEMO]',
    departamento: 'Enfermería',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
  {
    id: 'ASG-103',
    empleadoId: 'EMP-003',
    empleadoNombre: 'Lcda. Valentina Ríos Quintero',
    empleadoCargo: 'Coordinadora de Admisión y Caja [DEMO]',
    departamento: 'Administración',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
  {
    id: 'ASG-104',
    empleadoId: 'EMP-004',
    empleadoNombre: 'Dra. Elena Peralta Santos',
    empleadoCargo: 'Especialista en Pediatría [DEMO]',
    departamento: 'Médico',
    fecha: '2026-09-15',
    turnoId: 'TRN-02',
    turnoNombre: 'Tarde Asistencial (13:00 - 21:00) [DEMO]',
    tipoTurno: 'TARDE',
    estado: 'PROGRAMADO',
  },
  {
    id: 'ASG-105',
    empleadoId: 'EMP-005',
    empleadoNombre: 'Bioan. Carlos Gómez Benítez',
    empleadoCargo: 'Bioanalista Encargado [DEMO]',
    departamento: 'Laboratorio / Farmacia',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
  {
    id: 'ASG-106',
    empleadoId: 'EMP-006',
    empleadoNombre: 'Sr. Roberto Machado Gil',
    empleadoCargo: 'Supervisor de Mantenimiento [DEMO]',
    departamento: 'Operaciones / Servicios',
    fecha: '2026-09-15',
    turnoId: 'TRN-01',
    turnoNombre: 'Mañana Estándar (07:00 - 15:00) [DEMO]',
    tipoTurno: 'MANANA',
    estado: 'EN_CURSO',
  },
];

export const MOCK_REGISTROS_ASISTENCIA: RegistroAsistencia[] = [
  {
    id: 'AST-201',
    empleadoId: 'EMP-001',
    empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
    departamento: 'Médico',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '06:55',
    horaSalidaReal: '15:10',
    minutosRetardo: 0,
    horasTrabajadas: 8.25,
    horasExtras: 0.25,
    estado: 'PRESENTE',
    metodoMarcaje: 'BIOMETRICO_DEMO',
  },
  {
    id: 'AST-202',
    empleadoId: 'EMP-002',
    empleadoNombre: 'Lic. Mariana Contreras Silva',
    departamento: 'Enfermería',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '07:08',
    horaSalidaReal: '15:00',
    minutosRetardo: 8,
    horasTrabajadas: 7.86,
    horasExtras: 0,
    estado: 'RETARDO',
    justificacion: 'Congestión vehicular avenida principal [DEMO]',
    metodoMarcaje: 'PIN_TERMINAL',
  },
  {
    id: 'AST-203',
    empleadoId: 'EMP-003',
    empleadoNombre: 'Lcda. Valentina Ríos Quintero',
    departamento: 'Administración',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '06:50',
    horaSalidaReal: '15:00',
    minutosRetardo: 0,
    horasTrabajadas: 8.0,
    horasExtras: 0,
    estado: 'PRESENTE',
    metodoMarcaje: 'BIOMETRICO_DEMO',
  },
  {
    id: 'AST-204',
    empleadoId: 'EMP-005',
    empleadoNombre: 'Bioan. Carlos Gómez Benítez',
    departamento: 'Laboratorio / Farmacia',
    fecha: '2026-09-15',
    horaEntradaProgramada: '07:00',
    horaSalidaProgramada: '15:00',
    horaEntradaReal: '07:00',
    horaSalidaReal: '16:30',
    minutosRetardo: 0,
    horasTrabajadas: 9.5,
    horasExtras: 1.5,
    estado: 'PRESENTE',
    justificacion: 'Procesamiento de muestras urgentes de quirófano [DEMO]',
    metodoMarcaje: 'BIOMETRICO_DEMO',
  },
  {
    id: 'AST-205',
    empleadoId: 'EMP-007',
    empleadoNombre: 'Ing. Gabriela Salazar Uribe',
    departamento: 'Soporte y Sistemas',
    fecha: '2026-09-15',
    horaEntradaProgramada: '13:00',
    horaSalidaProgramada: '18:00',
    minutosRetardo: 0,
    horasTrabajadas: 0,
    horasExtras: 0,
    estado: 'VACACIONES',
    justificacion: 'Período vacacional anual aprobado [DEMO]',
    metodoMarcaje: 'MANUAL_SUPERVISOR',
  },
];

export const MOCK_METAS_PERSONAL: MetaPersonal[] = [
  {
    id: 'MET-01',
    titulo: 'Completitud de Diagnósticos CIE-10 en Historias [DEMO]',
    descripcion: 'Asegurar que las consultas ambulatorias registren su código CIE-10 principal para trazabilidad epidemiológica.',
    categoria: 'DOCUMENTACION_HISTORIAS',
    tipo: 'AUTOMATICA',
    origenMetrica: 'Motor de Historias Clínicas de Aurora Plus',
    departamentoObjetivo: 'Médico',
    metaValor: 95,
    unidadMedida: '% de historias',
    progresoActual: 96.5,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'COMPLETADA',
    esNoPunitiva: true,
    premioOReconocimiento: 'Reconocimiento a la excelencia en gestión de expedientes [DEMO]',
  },
  {
    id: 'MET-02',
    titulo: 'Tiempo Promedio de Triaje y Admisión < 7 min [DEMO]',
    descripcion: 'Optimizar la recepción de pacientes en sala de espera antes del llamado a consulta médica.',
    categoria: 'EFICIENCIA_PROCESOS',
    tipo: 'AUTOMATICA',
    origenMetrica: 'Registro de tiempos de check-in en Sala de Espera',
    departamentoObjetivo: 'Enfermería',
    metaValor: 7,
    unidadMedida: 'minutos',
    progresoActual: 6.2,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'COMPLETADA',
    esNoPunitiva: true,
    premioOReconocimiento: 'Mención de agilidad en reunión clínica mensual [DEMO]',
  },
  {
    id: 'MET-03',
    titulo: 'Puntualidad en Apertura de Caja Matutina [DEMO]',
    descripcion: 'Completar el fondo de caja y cuadre de tasas antes de las 07:15 AM de lunes a viernes.',
    categoria: 'PUNTUALIDAD',
    tipo: 'MANUAL',
    origenMetrica: 'Checklist de supervisión administrativa',
    departamentoObjetivo: 'Administración',
    metaValor: 20,
    unidadMedida: 'días puntuales',
    progresoActual: 18,
    fechaInicio: '2026-09-01',
    fechaLimite: '2026-09-30',
    estado: 'EN_PROGRESO',
    esNoPunitiva: true,
  },
  {
    id: 'MET-04',
    titulo: 'Capacitación en Protocolos de Bioseguridad Q3 [DEMO]',
    descripcion: 'Completar el módulo formativo digital de manejo de residuos biológicos y esterilización.',
    categoria: 'CAPACITACION',
    tipo: 'MANUAL',
    origenMetrica: 'Certificados emitidos en la plataforma de entrenamiento',
    departamentoObjetivo: 'TODOS',
    metaValor: 100,
    unidadMedida: '% del equipo',
    progresoActual: 78,
    fechaInicio: '2026-08-15',
    fechaLimite: '2026-09-30',
    estado: 'EN_PROGRESO',
    esNoPunitiva: true,
  },
];

export const MOCK_PERIODOS_NOMINA: PeriodoNomina[] = [
  {
    id: 'PER-2026-09-Q1',
    codigoPeriodo: 'NOM-2026-09-Q1',
    nombre: '1ra Quincena Septiembre 2026 [DEMO]',
    fechaInicio: '2026-09-01',
    fechaFin: '2026-09-15',
    fechaTentativaPago: '2026-09-15',
    estado: 'BORRADOR',
    totalEmpleados: 7,
    montoTotalBruto: 2400.0,
    montoTotalDeducciones: 180.0,
    montoTotalNeto: 2220.0,
    monedaPrincipal: 'USD',
    notasAuditoria: 'Período en cálculo preliminar sujeto a revisión de horas extras de guardia.',
    historialAjustes: [],
    recibos: [
      {
        id: 'REC-001',
        empleadoId: 'EMP-001',
        empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
        empleadoCargo: 'Médico Internista Principal [DEMO]',
        departamento: 'Médico',
        diasTrabajados: 15,
        horasExtrasTotal: 2,
        totalPercepciones: 630.0,
        totalDeducciones: 45.0,
        montoNetoPagar: 585.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base $1,200.00 mensual',
            reglaAplicada: 'Sueldo base / 2 (modalidad quincenal)',
            vigencia: 'Acuerdo contractual 2026 [DEMO]',
            monto: 600.0,
            moneda: 'USD',
          },
          {
            concepto: 'Bono Productividad y Cumplimiento de Metas [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: 'Meta CIE-10 superada al 96.5%',
            reglaAplicada: 'Monto fijo voluntario de estímulo profesional',
            vigencia: 'Política de incentivos clínicos Q3 [DEMO]',
            monto: 30.0,
            moneda: 'USD',
          },
          {
            concepto: 'Retención de Fondo de Salud / Seguro [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Aporte pactado voluntario para póliza colectiva',
            reglaAplicada: 'Cuota fija quincenal acordada',
            vigencia: 'Convenio de póliza interna 2026 [DEMO]',
            monto: 45.0,
            moneda: 'USD',
          },
        ],
      },
      {
        id: 'REC-002',
        empleadoId: 'EMP-002',
        empleadoNombre: 'Lic. Mariana Contreras Silva',
        empleadoCargo: 'Jefa de Enfermería y Triaje [DEMO]',
        departamento: 'Enfermería',
        diasTrabajados: 15,
        horasExtrasTotal: 4,
        totalPercepciones: 355.0,
        totalDeducciones: 25.0,
        montoNetoPagar: 330.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base $650.00 mensual',
            reglaAplicada: 'Sueldo base / 2 (modalidad quincenal)',
            vigencia: 'Tabulador Asistencial 2026 [DEMO]',
            monto: 325.0,
            moneda: 'USD',
          },
          {
            concepto: 'Compensación por Guardias Asistenciales [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '4 horas extraordinarias de soporte en triaje',
            reglaAplicada: 'Tarifa hora guardia acordada ($7.50 / h)',
            vigencia: 'Reglamento de turnos extendidos [DEMO]',
            monto: 30.0,
            moneda: 'USD',
          },
          {
            concepto: 'Deducción de Ahorro / Anticipo Solicitado [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Amortización cuota 1 de 2 de adelanto',
            reglaAplicada: 'Descuento directo autorizado por empleado',
            vigencia: 'Solicitud interna #419 [DEMO]',
            monto: 25.0,
            moneda: 'USD',
          },
        ],
      },
      {
        id: 'REC-003',
        empleadoId: 'EMP-003',
        empleadoNombre: 'Lcda. Valentina Ríos Quintero',
        empleadoCargo: 'Coordinadora de Admisión y Caja [DEMO]',
        departamento: 'Administración',
        diasTrabajados: 15,
        horasExtrasTotal: 0,
        totalPercepciones: 270.0,
        totalDeducciones: 20.0,
        montoNetoPagar: 250.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '15 días laborados sobre base $500.00 mensual',
            reglaAplicada: 'Sueldo base / 2',
            vigencia: 'Tabulador Administrativo [DEMO]',
            monto: 250.0,
            moneda: 'USD',
          },
          {
            concepto: 'Bono de Puntualidad y Cierre de Caja [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '100% de arqueos de caja sin diferencias en la quincena',
            reglaAplicada: 'Monto fijo de estímulo por cuadre perfecto',
            vigencia: 'Procedimiento de Tesorería [DEMO]',
            monto: 20.0,
            moneda: 'USD',
          },
          {
            concepto: 'Aporte de Uniforme y Credencial [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Reposición de dotación corporativa',
            reglaAplicada: 'Cuota fija convenio dotación',
            vigencia: 'Acuerdo de dotación [DEMO]',
            monto: 20.0,
            moneda: 'USD',
          },
        ],
      },
    ],
  },
  {
    id: 'PER-2026-08-Q2',
    codigoPeriodo: 'NOM-2026-08-Q2',
    nombre: '2da Quincena Agosto 2026 [DEMO]',
    fechaInicio: '2026-08-16',
    fechaFin: '2026-08-31',
    fechaTentativaPago: '2026-08-31',
    estado: 'APROBADA',
    aprobadoPor: 'Dirección Médica y Finanzas [DEMO]',
    fechaAprobacion: '2026-08-31 16:45',
    totalEmpleados: 7,
    montoTotalBruto: 2380.0,
    montoTotalDeducciones: 160.0,
    montoTotalNeto: 2220.0,
    monedaPrincipal: 'USD',
    notasAuditoria: 'Nómina auditada y cerrada. Pagos conciliados satisfactoriamente.',
    historialAjustes: [
      {
        id: 'AJU-001',
        fecha: '2026-08-31 16:45',
        tipoAccion: 'APROBACION_INICIAL',
        autor: 'Dra. Dirección Ejecutiva',
        motivoJustificado: 'Cierre regular de quincena sin discrepancias.',
      },
    ],
    recibos: [
      {
        id: 'REC-082-01',
        empleadoId: 'EMP-001',
        empleadoNombre: 'Dr. Alejandro Vargas Mendoza',
        empleadoCargo: 'Médico Internista Principal [DEMO]',
        departamento: 'Médico',
        diasTrabajados: 16,
        horasExtrasTotal: 0,
        totalPercepciones: 600.0,
        totalDeducciones: 45.0,
        montoNetoPagar: 555.0,
        moneda: 'USD',
        conceptosDesglosados: [
          {
            concepto: 'Sueldo Base Quincenal [DEMO]',
            tipo: 'PERCEPCION',
            baseCalculo: '16 días laborados',
            reglaAplicada: 'Sueldo base mensual / 2',
            vigencia: 'Tabulador 2026 [DEMO]',
            monto: 600.0,
            moneda: 'USD',
          },
          {
            concepto: 'Retención de Fondo de Salud [DEMO]',
            tipo: 'DEDUCCION',
            baseCalculo: 'Póliza colectiva acordada',
            reglaAplicada: 'Cuota fija quincenal',
            vigencia: 'Convenio 2026 [DEMO]',
            monto: 45.0,
            moneda: 'USD',
          },
        ],
      },
    ],
  },
];
